INSERT INTO tablepais (nome) VALUES ('Brasil');
INSERT INTO tablepais (nome) VALUES ('Estados Unidos');
INSERT INTO tablepais (nome) VALUES ('Suiça');
INSERT INTO tablepais (nome) VALUES ('Argentina');
INSERT INTO tablepais (nome) VALUES ('Jamaica');
INSERT INTO tablepais (nome) VALUES ('Portugal');
INSERT INTO tablepais (nome) VALUES ('Irlanda do Norte');

INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('América Futebol Clube', 'Belo Horizonte', 'MG', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Club Athletico Paranaense', 'Curitiba', 'PR', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Atlético Clube Goianiense', 'Goiânia', 'GO', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Clube Atlético Mineiro', 'Belo Horizonte', 'MG', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Avaí Futebol Clube', 'Florinópolis', 'SC', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Botafogo de Futebol e Regatas', 'Rio de Janeiro', 'RJ', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Red Bull Bragantino', 'Bragança Paulista', 'SP', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Ceará Sporting Clube', 'Fortaleza', 'CE', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Sport Club Corinthians Paulista', 'São Paulo', 'SP', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Coritiba Foot Ball Club', 'Curitiba', 'PR', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Cuiabá Esporte Clube', 'Cuiabá', 'MT', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Clube de Regatas do Flamengo', 'Rio de Janeiro', 'RJ', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Fluminense Football Club', 'Rio de Janeiro', 'RJ', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Fortaleza Esporte Clube', 'Fortaleza', 'CE', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Goiás Esporte Clube', 'Goiânia', 'GO', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Esporte Clube Juventude', 'Caxias do Sul', 'RS', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Sport Club Internacional', 'Porto Alegre', 'RS', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Sociedade Esportiva Palmeiras', 'São Paulo', 'SP', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('Santos Futebol Clube', 'Santos', 'SP', 1);
INSERT INTO tabletime (nome, cidade, estado, pais_id) VALUES ('São Paulo Futebol Clube', 'São Paulo', 'SP', 1);

INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Nike', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Rolex', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Credit Suisse', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Mercedes-Benz', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Upper Deck', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Callaway', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Barclays', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Exxon Mobile', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('McDonald’s', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Coca-Cola', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Samsung', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Beats by Dre', 1');
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Tencent', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Sprint', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('BBVA', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Panini', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('2K Sports', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('EA Games', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Omega', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Bose', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('TAG Heuer', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Herbalife', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Turkish Airlines', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Audemars Piget', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Adidas', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Gillette', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Pepsi', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Gatorede', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Hublot', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Virgin Media', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Visa', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Rexona', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Listerine', 1);
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Volkswagen', 1');
INSERT INTO tablepatrocinador (nome, pais_id) VALUES ('Panasonic', 1);

INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Carlos Alberto Gomes da Silva Filho', 'Atacante', 78.5 , 1.82, 700000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Nicolás Hernández', 'Zagueiro', 79.3 , 1.84, 800000.0, 1, 'Patrocínio', 1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Brian Montenegro', 'Atacante', 81.2 , 1.78, 550000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Edson Felipe da Cruz', 'Volante', 83.8 , 1.85, 575000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Bruno César Pereira da Silva', 'Volante', 89.9 , 1.77, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Matheus Nascimento de Paula', 'Atacante', 83.7 , 1.84, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Júlio César', 'Goleiro', 80.8 , 1.87, 539000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Messias Rodrigues da Silva Júnior', 'Zagueiro', 78.2 , 1.89, 650000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Cássio', 'Goleiro', 75.4 , 1.96, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Gustavo Costa da Silva Machado', 'Meio-campista', 88.5 , 1.81, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Gustavo Mantuan', 'Volante', 77.1 , 1.80, 900000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Rodrigo Caio', 'Zagueiro', 78.4 , 1.74, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Pedro Rangel', 'Goleiro', 90.7 , 1.89, 655000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Ángelo Henríquez', 'Atacante', 85.5 , 1.91, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Henrique Lordelo', 'Volante', 78.8 , 1.79, 400000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Paulo Henrique de Oliveira Alves', 'Lateral', 77.4 , 1.83, 790000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Andrés Nicolás DAlessandro', 'Meio-campista', 81.1 , 1.89, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Gabriel Veron', 'Atacante', 83.9 , 1.86, 690000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Lucas Braga', 'Ponta esquerda', 87.5 , 1.78, 800000.0, 1, 'Patrocínio',  1);
INSERT INTO tablejogador (nome, posicao, peso, altura, salario, patrocinio, descricao, time_id) VALUES ('Igor Gomes', 'Meio-campista', 81.2 , 1.80, 705000.0, 1, 'Patrocínio',  1);

INSERT INTO tablejogadorpatrocinador VALUES (1, 1);
INSERT INTO tablejogadorpatrocinador VALUES (1, 2);
INSERT INTO tablejogadorpatrocinador VALUES (1, 3);
INSERT INTO tablejogadorpatrocinador VALUES (2, 4);
INSERT INTO tablejogadorpatrocinador VALUES (2, 5);
INSERT INTO tablejogadorpatrocinador VALUES (2, 1);
INSERT INTO tablejogadorpatrocinador VALUES (2, 2);
INSERT INTO tablejogadorpatrocinador VALUES (3, 3);
INSERT INTO tablejogadorpatrocinador VALUES (3, 4);
INSERT INTO tablejogadorpatrocinador VALUES (4, 5);
INSERT INTO tablejogadorpatrocinador VALUES (4, 1);
INSERT INTO tablejogadorpatrocinador VALUES (4, 2);
INSERT INTO tablejogadorpatrocinador VALUES (5, 3);
INSERT INTO tablejogadorpatrocinador VALUES (5, 4);
INSERT INTO tablejogadorpatrocinador VALUES (5, 5);
INSERT INTO tablejogadorpatrocinador VALUES (5, 1);
INSERT INTO tablejogadorpatrocinador VALUES (6, 2);
INSERT INTO tablejogadorpatrocinador VALUES (6, 3);
INSERT INTO tablejogadorpatrocinador VALUES (6, 4);
INSERT INTO tablejogadorpatrocinador VALUES (7, 5);
INSERT INTO tablejogadorpatrocinador VALUES (8, 3);
INSERT INTO tablejogadorpatrocinador VALUES (8, 4);
INSERT INTO tablejogadorpatrocinador VALUES (8, 5);
INSERT INTO tablejogadorpatrocinador VALUES (8, 1);
INSERT INTO tablejogadorpatrocinador VALUES (8, 2);
INSERT INTO tablejogadorpatrocinador VALUES (9, 3);
INSERT INTO tablejogadorpatrocinador VALUES (9, 4);
INSERT INTO tablejogadorpatrocinador VALUES (9, 5);

INSERT INTO tableusuario (nome, sobrenome, email, senha) VALUES ('Alex', 'Brow', 'alex@gmail.com', '123');
INSERT INTO tableusuario (nome, sobrenome, email, senha) VALUES ('Maria', 'Green', 'maria@gmail.com', '123');

INSERT INTO tablefuncao (autoridade) VALUES ('ROLE_OPERATOR');
INSERT INTO tablefuncao (autoridade) VALUES ('ROLE_ADMIN');

INSERT INTO tableusuariofuncao (usuario_id, funcao_id) VALUES (1, 1);
INSERT INTO tableusuariofuncao (usuario_id, funcao_id) VALUES (2, 1);
INSERT INTO tableusuariofuncao (usuario_id, funcao_id) VALUES (2, 2);
